// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5WTwKFKi1I7KKTKfkK5WzP1vHZ-F4BCc',
    appId: '1:995858904118:web:b8f40f93c610c4efe45497',
    messagingSenderId: '995858904118',
    projectId: 'chat-app-cd506',
    authDomain: 'chat-app-cd506.firebaseapp.com',
    storageBucket: 'chat-app-cd506.appspot.com',
    measurementId: 'G-BDYYTMQ8N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2BYp4dSzu63oOT1zps2zitVzMzceV0VU',
    appId: '1:995858904118:android:983d5945f17b71cee45497',
    messagingSenderId: '995858904118',
    projectId: 'chat-app-cd506',
    storageBucket: 'chat-app-cd506.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvP_o9k4RKVqT7uts3lWNiw8UomaIp_8Y',
    appId: '1:995858904118:ios:93639f630eef8b11e45497',
    messagingSenderId: '995858904118',
    projectId: 'chat-app-cd506',
    storageBucket: 'chat-app-cd506.appspot.com',
    iosClientId: '995858904118-em6b54flfm36c9kf3ccvmu11rg9dhu2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvP_o9k4RKVqT7uts3lWNiw8UomaIp_8Y',
    appId: '1:995858904118:ios:93639f630eef8b11e45497',
    messagingSenderId: '995858904118',
    projectId: 'chat-app-cd506',
    storageBucket: 'chat-app-cd506.appspot.com',
    iosClientId: '995858904118-em6b54flfm36c9kf3ccvmu11rg9dhu2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp2',
  );
}
